name: A workflow for my Hello World file
on: push

jobs: 
    build: 
        name: Hellow world action
        runs-on: ubuntu-latest
        steps: 
            - users: actions/checkout@v1
            - users: ./action-a
              with: 
                MY_NAME: "Mona"
